### ISSUE TITLE
eldap dependency is missing

### ISSUE THREAD

**Issue by ghost** [rabbitmq/rabbitmq-auth-backend-ldap#109]
Hi,
I am new for RabbitMQ and Erlang and I am facing this error attached below while enabling rabbitmq we interface on localhost:15672 in my window10 64 bit pc. Please give any suggestions on this.

C:\Program Files\RabbitMQ Server\rabbitmq_server-3.7.14\sbin>rabbitmq-plugins enable rabbitmq_management
Enabling plugins on node rabbit@KT-PC-249:
rabbitmq_management
The following plugins have been configured:
  rabbitmq_auth_backend_ldap
  rabbitmq_management
  rabbitmq_management_agent
  rabbitmq_web_dispatch
Applying plugin configuration to rabbit@KT-PC-249...
** (CaseClauseError) no case clause matching: {:error, {:missing_dependencies, [:eldap], [:rabbitmq_auth_backend_ldap]}}
    (rabbitmqctl) lib/rabbitmq/cli/plugins/plugins_helpers.ex:115: RabbitMQ.CLI.Plugins.Helpers.update_enabled_plugins/4
    (rabbitmqctl) lib/rabbitmq/cli/plugins/commands/enable_command.ex:129: anonymous fn/6 in RabbitMQ.CLI.Plugins.Commands.EnableCommand.do_run/2
    (elixir) lib/stream.ex:1311: anonymous fn/2 in Stream.iterate/2
    (elixir) lib/stream.ex:1497: Stream.do_unfold/4
    (elixir) lib/stream.ex:1568: Enumerable.Stream.do_each/4
    (elixir) lib/stream.ex:936: Stream.do_enum_transform/7
    (elixir) lib/stream.ex:1568: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:1990: Enum.reduce_while/3

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
From the [doc guide](https://www.rabbitmq.com/ldap.html#prerequisites):

```
RabbitMQ LDAP plugin depends on an LDAP client called eldap. The library ships
with Erlang/OTP. On some operating systems, some Erlang components must
be installed separately from the core runtime.
```

**Comment by michaelklishin** [comment]
In other words, you have the LDAP plugin enabled but your Erlang installation is missing `eldap`, which leads any plugin dependency resolution operation (which has to happen when you enable `rabbitmq_management`) to fail.

This is most common on Ubuntu and Debian which love to slice and dice standard libraries, see the doc guide above. Standard Erlang packages for Windows should include `eldap` in the installer.

**Comment by ghost** [comment]
Thanks its works by giving full read & writes access for erlang folder and then reinstalling.

**Comment by michaelklishin** [comment]
Thank you for reporting back.
