### ISSUE TITLE
Support a filter for authentication

### ISSUE THREAD

**Issue by travisghansen** [rabbitmq/rabbitmq-auth-backend-ldap#74]
Most of the integrations I do with ldap allow for applying a filter (ie: memberOf=<group>).  I'm not seeing that option here.  Am I just missing that?

Thanks!

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
See [LDAP plugin documentation](http://www.rabbitmq.com/ldap.html), all supported query types are listed there.

**Comment by travisghansen** [comment]
@michaelklishin it's less of a question and more of a statement.  It's general functionality that isn't available in rabbitmq.  I see that group membership can be used for tags, resources, and vhosts (authorization) which I am doing, but **not** authentication.  That is the request.  Regardless I can post to the user list.

**Comment by michaelklishin** [comment]
@travisghansen this is a question as posted originally (at least as defined by this team) but anyway.

RabbitMQ authn backends take a username and a map of additional arguments. In LDAP this means expanding variables and applying an [equality filter](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/master/src/rabbit_auth_backend_ldap.erl#L700). It's not clear to me how exactly group membership would work/be used for *authentication* and this team does not use GitHub issues for discussions.

**Comment by michaelklishin** [comment]
It's possible to use group membership in vhost access query today — which is not authentication but happens right after it, before a connection can do anything — which is possibly why group membership in authentication request isn't common.

**Comment by travisghansen** [comment]
@michaelklishin agreed for vhosts.  That's a fair argument.  I guess I'd prefer to straight up reject authentication (some examples):

https://docs.gitlab.com/ce/administration/auth/ldap.html#using-an-ldap-filter-to-limit-access-to-your-gitlab-server
https://www.npmjs.com/package/node-red-contrib-ldap-auth
https://github.com/matrix-org/matrix-synapse-ldap3
https://docs.nextcloud.com/server/12/admin_manual/configuration_user/user_auth_ldap.html
pretty much any VPN, etc, etc all support the filter idea.

Anyhow, thanks for the consideration!

**Comment by michaelklishin** [comment]
GitLab's guide says "limit access", which means "authentication" to some and "authorization" to others. In RabbitMQ's case, vhost access query is technically an authorization step but I think it counts for "limiting access" nonetheless.

Perhaps it's a common thing to conflate the two in LDAP-based systems, I'm not an LDAP expert by any stretch.

**Comment by travisghansen** [comment]
@michaelklishin all of those apps behave as if the user does not exist at all in the directory.  The context/scope of that specific block is authentication.
